// Resolves Simple Icons slugs and vendors the path data into
// src/data/icons.ts so the build makes no network request at all.
//
//   node scripts/fetch-icons.mjs
//
// Vendored rather than fetched during `astro build`: pinning the paths keeps
// builds reproducible and offline-capable, and `@latest` would otherwise let
// a mark change silently between two builds of the same commit.

import { writeFile, mkdir } from 'node:fs/promises';

// Candidate slugs per label, tried in order. Simple Icons drops marks whose
// trademark holders object, and some entries here are not brands at all.
const ITEMS = [
  ['Python', ['python']],
  ['TypeScript', ['typescript']],
  ['JavaScript', ['javascript']],
  ['Java', ['java', 'openjdk']],
  ['C++', ['cplusplus']],
  ['SQL', ['sql']],
  ['Bash', ['gnubash', 'bash']],
  ['HTML', ['html5', 'html']],
  ['CSS', ['css', 'css3']],
  ['FastAPI', ['fastapi']],
  ['Flask', ['flask']],
  ['Node.js', ['nodedotjs', 'node-dot-js']],
  ['Express', ['express']],
  ['PostgreSQL', ['postgresql']],
  ['MongoDB', ['mongodb']],
  ['Docker', ['docker']],
  ['AWS', ['amazonwebservices', 'amazonaws', 'aws']],
  ['PyTorch', ['pytorch']],
  ['TensorFlow', ['tensorflow']],
  ['Hugging Face Transformers', ['huggingface']],
  ['scikit-learn', ['scikitlearn']],
  ['NumPy', ['numpy']],
  ['Pandas', ['pandas']],
  ['Jupyter', ['jupyter']],
  ['React', ['react']],
  ['Vite', ['vite']],
  ['Redux', ['redux']],
  ['Tailwind', ['tailwindcss']],
  ['Git', ['git']],
  ['GitHub', ['github']],
  ['Linux', ['linux']],
  ['LaTeX', ['latex']],
];

const BASE = 'https://cdn.jsdelivr.net/npm/simple-icons@latest/icons';

const resolved = {};
const missing = [];

for (const [label, slugs] of ITEMS) {
  let hit = null;
  for (const slug of slugs) {
    const res = await fetch(`${BASE}/${slug}.svg`);
    if (!res.ok) continue;
    const svg = await res.text();
    const d = svg.match(/\sd="([^"]+)"/)?.[1];
    const title = svg.match(/<title>([^<]*)<\/title>/)?.[1] ?? slug;
    if (d) {
      hit = { slug, d, title };
      break;
    }
  }
  if (hit) {
    resolved[label] = hit;
    console.log(`  ok      ${label.padEnd(28)} ${hit.slug}`);
  } else {
    missing.push(label);
    console.log(`  MISSING ${label.padEnd(28)} tried ${slugs.join(', ')}`);
  }
}

await mkdir('src/data', { recursive: true });
const out = `// Generated by scripts/fetch-icons.mjs. Do not edit by hand.
//
// Simple Icons path data, vendored so the build makes no network request.
// Simple Icons is CC0 1.0; each mark is the project's own, used here to
// identify that project, which is what the set is for.
//
// Labels with no mark in the set render as text chips instead. A generic mark
// is never substituted: nobody recognises an abstract shape as Docker, and a
// wrong-looking mark is worse than an honest word.
${missing.length ? `//\n// No mark available: ${missing.join(', ')}\n` : ''}
export interface SimpleIcon {
  slug: string;
  d: string;
  title: string;
}

export const ICONS: Record<string, SimpleIcon> = ${JSON.stringify(resolved, null, 2)};
`;
await writeFile('src/data/icons.ts', out);

console.log(`\n  resolved ${Object.keys(resolved).length}, missing ${missing.length}`);
if (missing.length) console.log(`  text chips: ${missing.join(', ')}`);
